/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
        "colors": {
            "on-background": "#dfe2f1",
            "outline-variant": "#464555",
            "error-container": "#93000a",
            "secondary": "#adc6ff",
            "on-error": "#690005",
            "surface-container": "#1c1f2a",
            "on-primary": "#1d00a5",
            "surface-container-high": "#262a35",
            "tertiary-fixed": "#ffdbcc",
            "surface-container-low": "#171b26",
            "error": "#ffb4ab",
            "on-secondary": "#002e6a",
            "secondary-fixed-dim": "#adc6ff",
            "on-tertiary": "#571f00",
            "surface-dim": "#0f131d",
            "secondary-container": "#0566d9",
            "on-tertiary-fixed-variant": "#7b2f00",
            "tertiary": "#ffb695",
            "surface": "#0f131d",
            "on-tertiary-container": "#ffd2be",
            "primary-fixed-dim": "#c3c0ff",
            "surface-bright": "#353944",
            "tertiary-fixed-dim": "#ffb695",
            "on-secondary-fixed": "#001a42",
            "on-tertiary-fixed": "#351000",
            "inverse-primary": "#4d44e3",
            "on-surface-variant": "#c7c4d8",
            "on-secondary-container": "#e6ecff",
            "on-secondary-fixed-variant": "#004395",
            "outline": "#918fa1",
            "inverse-surface": "#dfe2f1",
            "secondary-fixed": "#d8e2ff",
            "surface-tint": "#c3c0ff",
            "surface-container-highest": "#313540",
            "surface-variant": "#313540",
            "on-error-container": "#ffdad6",
            "primary-container": "#4f46e5",
            "primary": "#c3c0ff",
            "primary-fixed": "#e2dfff",
            "on-primary-fixed": "#0f0069",
            "surface-container-lowest": "#0a0e18",
            "tertiary-container": "#a44100",
            "inverse-on-surface": "#2c303b",
            "on-primary-container": "#dad7ff",
            "on-primary-fixed-variant": "#3323cc",
            "background": "#0f131d",
            "on-surface": "#dfe2f1"
        },
        "borderRadius": {
            "DEFAULT": "0.25rem",
            "lg": "0.5rem",
            "xl": "0.75rem",
            "full": "9999px"
        },
        "spacing": {
            "gutter": "16px",
            "xl": "64px",
            "md": "24px",
            "xs": "8px",
            "sm": "16px",
            "margin-mobile": "20px",
            "margin-desktop": "48px",
            "base": "4px",
            "lg": "40px",
            "bottom-bar-height": "72px",
            "sidebar-width": "280px"
        },
        "fontFamily": {
            "label-caps": ["Geist"],
            "headline-lg": ["Space Grotesk"],
            "mono-data": ["Geist"],
            "headline-md": ["Space Grotesk"],
            "headline-lg-mobile": ["Space Grotesk"],
            "body-md": ["Inter"],
            "body-lg": ["Inter"]
        },
        "fontSize": {
            "label-caps": ["12px", { "lineHeight": "1.0", "letterSpacing": "0.1em", "fontWeight": "600" }],
            "headline-lg": ["40px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
            "mono-data": ["14px", { "lineHeight": "1.4", "fontWeight": "500" }],
            "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
            "headline-lg-mobile": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
            "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
            "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }]
        }
    },
  },
  plugins: [],
}
