import { precacheAndRoute } from 'workbox-precaching';

// Inject the precache manifest generated by Vite PWA plugin
precacheAndRoute(self.__WB_MANIFEST || []);

self.addEventListener('install', (event) => {
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
});

// If you want to move the IndexedDB background sync logic directly into the service worker 
// (using Background Sync API), you can listen for the 'sync' event here.
// For now, our frontend App.jsx triggers `syncOfflineQueue` on the window 'online' event.
self.addEventListener('sync', (event) => {
  if (event.tag === 'sync-reports') {
    // We would call the sync logic here if registered via serviceWorker.ready
    console.log('Background sync triggered for offline reports');
  }
});
